[project]
name = "spatial-audio-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "analysis",
    "mediapipe>=1.0.1",
    "piper-tts>=1.7.0",
    "spatial-audio",
]

[tool.uv.sources]
analysis = { path = "../analysis", editable = true }
spatial-audio = { path = "../spatial-audio", editable = true }
